
POST {{$processEnv COMMITLOGGER_QUEUE_URL}} HTTP/1.1
Content-Type: text/xml

<QueueMessage><MessageText>
{"commit_hash": "aaafe8da06ab8ec6cc79b34e6aacc28f595a22af", "repository": "fake repository", "branch": "main", "author": "Christian Dalager", "commit_message": "test hook"}
</MessageText></QueueMessage> 
